### ISSUE TITLE
Jaspermobile android 1.8 shows blank reports

### ISSUE THREAD

**Issue by degrashopper** [Jaspersoft/js-android-app#2]
Last week we updated the jasperserver from 5.5.0 to 5.6.0 (community version). After the update reports on the jaspermobile app show up blank. The blue bar at the top shows that the report is loading. After that the report stays blank. The IOS version works fine.

**Comment by tomkoptel** [comment]
Issue was fixed in release of app version 1.9. 
* On the servers version 5.6.0 we are exposing image of graphic and this is the only possible fix for this.
* On the servers versions 5.5 and 5.6.1+ reports work properly
