### ISSUE TITLE
401 problem

### ISSUE THREAD

**Issue by bilalakcay** [Jaspersoft/js-android-app#9]
The app gets 401 error when the repository or library accessed on mobiledemo.jaspersoft.com 
The source is compiled with "gradle installProductionDebug" and installed on device after downloading from github.

Jaspersoft mobile app downloaded from Google Play works well.

**Comment by tomkoptel** [comment]
Hi @bilalakcay ! 

The issue you reproduced due to the master app/build.gradle script was pointing on the snapshot version of SDK 1.9.1. 
Issue fixed you may pull changes and build app again from master branch.

Best regrads!

**Comment by tomkoptel** [comment]
I will close an issue due to no reponse.
